(function(global){
  'use strict';
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),midi=n=>440*Math.pow(2,(n-69)/12);
  function hash(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
  function env(g,t,a,l,d,r=.08){g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,l),t+a);g.gain.setValueAtTime(Math.max(.0002,l*.68),Math.max(t+a,t+d-r));g.gain.exponentialRampToValueAtTime(.0001,t+d)}
  function noise(ctx,d,seed){const b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*d),ctx.sampleRate),x=b.getChannelData(0),r=rng(seed);for(let i=0;i<x.length;i++)x[i]=r()*2-1;return b}
  function out(ctx,dest,pan){const p=ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain();if(p.pan)p.pan.value=clamp(pan,-.85,.85);p.connect(dest);return p}
  function osc(ctx,dest,type,f,t,d,l,a=.01,detune=0){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.detune.value=detune;env(g,t,a,l,d);o.connect(g).connect(dest);o.start(t);o.stop(t+d+.05)}
  function voice(ctx,dest,id,note,t,dur,vel,seed,pan){const safeNote=clamp(note,id==='dizi'?50:43,id==='dizi'?76:81),f=midi(safeNote),o=out(ctx,dest,pan),r=rng(seed),d=Math.max(.09,dur),v=clamp(vel,.012,.42);
    if(id==='qin'){const lp=ctx.createBiquadFilter();lp.type='lowpass';lp.frequency.value=1550;lp.Q.value=.45;lp.connect(o);osc(ctx,lp,'triangle',f,t,d,v*.88,.012,-4);osc(ctx,lp,'sine',f*2.005,t,d*.66,v*.2,.008,3);osc(ctx,lp,'sine',f*.5,t,d*.88,v*.18,.018)}
    else if(id==='pipa'){const hp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=125;lp.type='lowpass';lp.frequency.value=2600;hp.connect(lp).connect(o);[0,.045].forEach((q,i)=>osc(ctx,hp,i?'sine':'triangle',f*(1+i*.004),t+q,Math.min(.74,d),v*(i?.16:.62),.008,(r()-.5)*3))}
    else if(id==='xiao'||id==='dizi'){const bp=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter(),g=ctx.createGain(),s=ctx.createBufferSource();bp.type='bandpass';bp.frequency.value=id==='dizi'?Math.min(2600,f*2.25):Math.min(1800,f*1.55);bp.Q.value=id==='dizi'?1.25:.9;lp.type='lowpass';lp.frequency.value=id==='dizi'?3300:2300;bp.connect(lp).connect(g).connect(o);s.buffer=noise(ctx,d,seed);env(g,t,.07,v*(id==='dizi'?.055:.1),d,.18);s.connect(bp);s.start(t);s.stop(t+d+.02);osc(ctx,o,'sine',f,t,d,v*(id==='dizi'?.56:.7),id==='dizi'?.055:.14,(r()-.5)*3);osc(ctx,o,'sine',f*2,t+.018,d*.78,v*(id==='dizi'?.08:.04),.07)}
    else if(id==='sheng'){[0,7,12].forEach((semi,i)=>osc(ctx,o,'sine',midi(safeNote+semi),t,d,v/(2+i*.8),.18,(r()-.5)*3))}
    else if(id==='bell'||id==='stone'){const lp=ctx.createBiquadFilter();lp.type='lowpass';lp.frequency.value=id==='bell'?3200:2500;lp.Q.value=.4;lp.connect(o);(id==='bell'?[1,2.01,2.98]:[1,1.5,2.01]).forEach((q,i)=>osc(ctx,lp,'sine',f*q,t,Math.min(d*(1.08+i*.18),3.2),v*[.62,.17,.08][i],.008+i*.006))}
    else{const g=ctx.createGain(),z=ctx.createOscillator();z.type='sine';z.frequency.setValueAtTime(f*.62,t);z.frequency.exponentialRampToValueAtTime(Math.max(42,f*.22),t+.16);env(g,t,.003,v,Math.min(.58,d),.18);z.connect(g).connect(o);z.start(t);z.stop(t+.64);const s=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),ng=ctx.createGain();s.buffer=noise(ctx,.16,seed);lp.type='lowpass';lp.frequency.value=520;env(ng,t,.002,v*.36,.16,.08);s.connect(lp).connect(ng).connect(o);s.start(t);s.stop(t+.18)}
  }
  function drone(ctx,dest,note,t,dur,level,pan=0){const o=out(ctx,dest,pan),f=midi(note);osc(ctx,o,'sine',f,t,dur,level,.18,-2);osc(ctx,o,'sine',f*2,t,dur,level*.16,.24,3)}
  function makeBus(ctx,volume=.78){const input=ctx.createGain(),tone=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor(),master=ctx.createGain(),an=ctx.createAnalyser(),delay=ctx.createDelay(1),feed=ctx.createGain(),wet=ctx.createGain();tone.type='lowpass';tone.frequency.value=5200;tone.Q.value=.25;comp.threshold.value=-20;comp.knee.value=18;comp.ratio.value=4;comp.attack.value=.012;comp.release.value=.28;master.gain.value=volume;an.fftSize=1024;delay.delayTime.value=.31;feed.gain.value=.13;wet.gain.value=.12;input.connect(tone).connect(comp);input.connect(delay);delay.connect(feed).connect(delay);delay.connect(wet).connect(tone);comp.connect(master).connect(an).connect(ctx.destination);return{input,master,analyser:an,wet,tone}}
  class AxisAudioEngine{
    constructor(params,onTick){this.p=params;this.onTick=onTick||(()=>{});this.active=new Set(['qin','xiao','sheng']);this.mainTimbre='qin';this.score=null;this.performance=null;this.nodeIndex=0;this.playing=false;this.volume=params.mix.default_volume;this.reverb=.42;this.tempoFactor=1;this.phraseCycle=0;this.renderCache=new Map()}
    async init(){if(this.ctx){if(this.ctx.state==='suspended')await this.ctx.resume();return}const AC=global.AudioContext||global.webkitAudioContext;if(!AC)throw Error('AudioContext unavailable');this.ctx=new AC();Object.assign(this,makeBus(this.ctx,this.volume));await this.ctx.resume()}
    setScore(score){this.score=score}
    setSemantic(semantic){this.semantic=semantic||{};if(this.semantic.timePulse)this.setTempoFactor(.92);if(this.wet)this.wet.gain.setTargetAtTime(clamp(.04+this.reverb*.3+(this.semantic.reverbAdd||0),.02,.42),this.ctx.currentTime,.08)}
    setPerformance(p){this.performance=p}
    setMainTimbre(id){this.mainTimbre=id;if(!this.active.has(id)){const a=[id,...this.active].slice(0,4);this.active=new Set(a)}this.onTick(this.snapshot())}
    setEnsemble(ids){this.active=new Set(ids.slice(0,4));this.mainTimbre=ids[0]||'qin';this.onTick(this.snapshot())}
    toggleInstrument(id){if(this.active.has(id)){if(this.active.size>1)this.active.delete(id)}else{if(this.active.size>=4)return false;this.active.add(id)}this.preview(id);this.onTick(this.snapshot());return true}
    async intro(){await this.init();const t=this.ctx.currentTime+.04,opening=this.themeMelody().filter(e=>e.phraseIndex===0),beat=.28;voice(this.ctx,this.input,'bell',52,t,2.15,.07,21,-.45);voice(this.ctx,this.input,'sheng',48,t,2.7,.075,22,.08);opening.forEach((e,i)=>voice(this.ctx,this.input,i<3?'qin':'xiao',e.pitchMidi,t+e.phraseBeat*beat,Math.max(.24,e.durationBeats*beat*.92),.125+(e.phraseRole==='cadence'?.015:0),23+i,(i-opening.length/2)/14))}
    async preview(id){await this.init();const es=this.themeMelody().filter(e=>e.phraseIndex===0),t=this.ctx.currentTime+.04,beat=.34;(es.length?es:[{pitchMidi:64,durationBeats:.5,phraseBeat:0},{pitchMidi:64,durationBeats:.5,phraseBeat:.5},{pitchMidi:67,durationBeats:1,phraseBeat:1}]).forEach((e,i)=>voice(this.ctx,this.input,id,e.pitchMidi,t+(e.phraseBeat||0)*beat,Math.min(1.15,e.durationBeats*beat*.92),.15,hash(id+i+e.pitchMidi),(i-es.length/2)/18))}
    async previewTheme(){await this.init();const es=this.themeMelody().filter(e=>e.phraseIndex===0),t=this.ctx.currentTime+.04,beat=60/84,lead=this.leadForNode(this.nodeIndex);if(!es.length)return;drone(this.ctx,this.input,48,t,6.2,.014,0);es.forEach(e=>this.scheduleEvent(this.ctx,this.input,e,t+e.phraseBeat*beat,lead,.66,{durationFactor:.96,harmony:e.phraseRole==='cadence',bass:false}))}
    playHistory(nodeId,depth=2){if(!this.ctx)return;const index=11-Number(nodeId.slice(1)),chapter=this.themeMelody().filter(e=>e.nodeId===nodeId),fallback=this.melodyForNode(index),pick=(n=0)=>chapter[n%Math.max(1,chapter.length)]||fallback[n%Math.max(1,fallback.length)],t=this.ctx.currentTime+.06;
      if(nodeId==='N06'){const e=pick(0);this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-24,harmony:[e.pitchMidi-24]},t,'drum',.13,{bass:false});this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t+.18,'bell',.095,{durationFactor:1.18,bass:false});this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t+.48,'sheng',.065,{durationFactor:1.45,bass:false})}
      else if(nodeId==='N04'){[0,1,2].forEach((n,i)=>{const e=pick(n);this.scheduleEvent(this.ctx,this.input,{...e,harmony:[e.pitchMidi]},t+i*.56,i===0?'qin':i===1?'stone':'xiao',.1,{durationFactor:1.02,bass:false})})}
      else if(nodeId==='N02'){const e=pick(0);[0,.72,1.44].forEach((q,i)=>this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t+q,i%2?'stone':'bell',.07,{durationFactor:.78,bass:false}))}
      else if(nodeId==='N03'){[0,1,2,3].forEach((n,i)=>{const e=pick(n);this.scheduleEvent(this.ctx,this.input,{...e,harmony:[e.pitchMidi]},t+i*.42,i%3?'qin':'xiao',.07,{durationFactor:.9,bass:false})})}
      else{const e=pick(0);if(e)this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t,nodeId==='N11'?'xiao':nodeId==='N01'?'qin':'stone',depth===3?.1:.075,{durationFactor:1.08,bass:false})}}
    eventsForNode(index){const id='N'+String(11-index).padStart(2,'0');return this.score?.events.filter(e=>e.nodeId===id&&e.layer==='geometry')||[]}
    themeMelody(){return(this.score?.events||[]).filter(e=>e.layer==='theme'&&e.melodicPriority!==false).sort((a,b)=>a.phraseBeat-b.phraseBeat||a.id.localeCompare(b.id))}
    profileForNode(index){const id='N'+String(11-index).padStart(2,'0'),cfg=this.p.score?.node_motifs?.[id]||{},node=(this.p.nodes||this.p.events||[]).find(n=>n.id===id)||{};return{id,name:cfg.name||node.cn||node.label||id,tempo:this.p.mix.default_bpm||84,phraseBeats:this.score?.themeBeats||48,accent:cfg.accent||this.mainTimbre,kind:node.kind||'殿',zone:node.zone||'',act:index<=4?1:index<=7?2:3,energy:node.narrative?.energy??.6}}
    melodyForNode(index){const p=this.profileForNode(index),geometry=this.eventsForNode(index),stats=geometry[0]?.architectureControl||geometry.reduce((out,e,i,a)=>{for(const k of['density','span','enclosure','symmetry','center'])out[k]=(out[k]||0)+(e.sourceGeometry?.[k]||0)/a.length;return out},{density:.5,span:.5,enclosure:.5,symmetry:.5,center:.5});return this.themeMelody().map(e=>{const cadence=e.phraseRole==='cadence',harmony=cadence&&stats.symmetry>.58?[e.pitchMidi,e.pitchMidi+7]:[e.pitchMidi];return{...e,nodeId:p.id,nodeMotif:p.name,nodeAccent:p.accent,nodeTempo:this.p.mix.default_bpm||84,velocity:clamp(e.velocity*(.78+p.energy*.26),.36,.86),durationBeats:e.durationBeats*(.88+stats.enclosure*.16),harmony,bassWeight:.12+stats.center*.38,architectureControl:{...stats,shadowRegister:stats.span>.72?1:stats.span<.28?-1:0}}})}
    leadForNode(index,activeOverride){const selected=activeOverride?.length?[...activeOverride]:[...this.active],melodic=['qin','pipa','xiao','dizi','sheng','bell','stone'];if(melodic.includes(this.mainTimbre)&&selected.includes(this.mainTimbre))return this.mainTimbre;const p=this.profileForNode(index);if(melodic.includes(p.accent)&&selected.includes(p.accent))return p.accent;return selected.find(id=>melodic.includes(id))||(['sheng','bell','qin'][p.act-1])}
    phraseExcerpt(events,index,speed=0){const phraseIndex=this.phraseCycle%6,phrase=events.filter(e=>e.phraseIndex===phraseIndex);if(speed>.85&&phrase.length>6)return phrase.filter((_,i)=>i%2===0||i===phrase.length-1);return phrase}
    previousNode(index){const order=this.performance?.routeOrder||[],prior=order.filter(i=>i!==index);return prior.length?prior[prior.length-1]:null}
    paletteForNode(index,activeOverride){const p=this.profileForNode(index),maps={N11:['xiao','drum','sheng'],N10:['drum','sheng','pipa'],N09:['pipa','drum','sheng'],N08:['drum','bell','sheng'],N07:['sheng','stone','pipa'],N06:['bell','stone','sheng','pipa'],N05:['xiao','qin','sheng'],N04:['stone','pipa','bell'],N03:['qin','xiao','stone'],N02:['stone','bell','qin'],N01:['qin','xiao','sheng']};const stage=maps[p.id]||[p.accent,'qin','sheng'],selected=activeOverride?.length?[...activeOverride]:[...this.active],ordered=[...selected.filter(id=>stage.includes(id)),...stage,...selected];return[...new Set(ordered)].slice(0,4)}
    setNode(node,index){this.nodeIndex=index;if(this.playing&&this.ctx){const now=this.ctx.currentTime;if(this.master){this.master.gain.cancelScheduledValues(now);this.master.gain.setTargetAtTime(Math.max(.02,this.volume*.38),now,.035);this.master.gain.setTargetAtTime(this.volume,now+.16,.09)}}else this.playArrival(index);this.onTick(this.snapshot())}
    playArrival(index){if(!this.ctx||this.playing)return;const es=this.phraseExcerpt(this.melodyForNode(index),index,.9),p=this.profileForNode(index),lead=this.leadForNode(index),t=this.ctx.currentTime+.025;if(!es.length)return;const beat=60/((this.p.mix.default_bpm||76)*this.tempoFactor);es.slice(0,3).forEach((e,i)=>this.scheduleEvent(this.ctx,this.input,e,t+e.phraseBeat*beat,lead,(.62+i*.05)*(p.energy+.28),{realtime:true,nodeIndex:index,harmony:i===2}))}
    setTempoFactor(v){this.tempoFactor=clamp(v,.72,1.38)}
    setVolume(v){this.volume=clamp(Number(v),0,1);if(this.master)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.04)}
    setReverb(v){this.reverb=clamp(Number(v),0,1);if(this.wet)this.wet.gain.setTargetAtTime(.04+this.reverb*.3,this.ctx.currentTime,.05)}
    async start(){await this.init();if(this.playing)return;this.playing=true;this.phraseStart=this.ctx.currentTime+.05;this.cycleStart=this.phraseStart;this.nextPhraseEvent=0;this.phraseCycle=0;this.timer=setInterval(()=>this.schedule(),45);this.onTick(this.snapshot())}
    pause(){this.playing=false;clearInterval(this.timer);this.onTick(this.snapshot())}
    async restart(){this.pause();await this.start()}
    schedule(){if(!this.playing||!this.score)return;const melody=this.melodyForNode(this.nodeIndex),p=this.profileForNode(this.nodeIndex);if(!melody.length)return;const beat=60/((this.p.mix.default_bpm||84)*this.tempoFactor),phraseDur=(this.score.themeBeats||48)*beat,lead=this.leadForNode(this.nodeIndex),palette=this.paletteForNode(this.nodeIndex),response=palette.find(id=>id!==lead&&id!=='drum');while(this.nextPhraseEvent<melody.length){const e=melody[this.nextPhraseEvent],t=this.phraseStart+e.phraseBeat*beat;if(t>this.ctx.currentTime+.24)break;const on=Math.max(t,this.ctx.currentTime+.006),motion=.92+Math.min(.22,(this.performance?.dwellByNode?.[this.nodeIndex]||0)/30000);this.scheduleEvent(this.ctx,this.input,e,on,lead,(.64+p.energy*.2)*motion,{realtime:true,nodeIndex:this.nodeIndex,harmony:e.phraseRole==='cadence'});if(e.phraseRole==='opening'){const pedal={...e,pitchMidi:Math.max(43,e.pitchMidi-12),durationBeats:Math.min(4,e.durationBeats*2.5),bassWeight:.15};this.scheduleEvent(this.ctx,this.input,pedal,on,p.act===3?'qin':'sheng',.105+p.energy*.035,{realtime:true,durationFactor:1.32,bass:false});if(p.kind==='门')this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:Math.max(43,e.pitchMidi-24),durationBeats:.34},on,'drum',.12+p.energy*.05,{realtime:true,durationFactor:.58,bass:false})}if(response&&e.phraseRole==='cadence')this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:e.pitchMidi-12},on+.065,response,.075,{realtime:true,durationFactor:1.15,bass:false});this.nextPhraseEvent++}if(this.nextPhraseEvent>=melody.length&&this.ctx.currentTime>this.phraseStart+phraseDur-.26){this.phraseStart+=phraseDur;this.cycleStart=this.phraseStart;this.nextPhraseEvent=0;this.phraseCycle++}this.onTick(this.snapshot())}
    scheduleEvent(ctx,dest,e,t,id,mod=.8,options={}){const sem={...(e.semanticMod||{}),...(options.realtime?(this.semantic||{}):{})},durationFactor=options.durationFactor||1,dur=Math.min(4,e.durationBeats*.56*durationFactor*(.86+this.reverb*.25)*(1+(sem.intimacy||0)*.06)),basePan=((e.motifStep||0)%7-3)/11,pan=options.panReverse?-basePan:basePan;voice(ctx,dest,id,e.pitchMidi,t,dur,e.velocity*.27*mod*(sem.energyFactor||1),hash(e.id+'|'+id),pan);if(e.timbreRole==='ritual_resonance'&&e.harmony?.length>1&&(options.harmony||e.phraseRole==='cadence'))voice(ctx,dest,id,Math.min(76,e.harmony[1]),t+.055,dur*1.02,e.velocity*.042*mod,hash(e.id+'h'),-pan*.45);if(options.bass!==false&&e.bassWeight>.38&&id!=='drum'&&(e.phraseRole==='opening'||e.phraseRole==='cadence'))voice(ctx,dest,'sheng',e.pitchMidi-12,t,dur*1.14,e.velocity*.032*mod,hash(e.id+'b'),0)}
    waveform(a){if(!this.analyser)return a.fill(128);this.analyser.getByteTimeDomainData(a);return a}
    snapshot(){const beat=60/((this.p.mix.default_bpm||84)*this.tempoFactor),elapsed=Math.max(0,(this.ctx?.currentTime||0)-(this.phraseStart||0)),themeBeat=(elapsed/beat)%(this.score?.themeBeats||48),themePhrase=Math.min(6,Math.floor(themeBeat/8)+1);return{playing:this.playing,bar:Math.floor(themeBeat/4)+1,themeBeat,themePhrase,active:[...this.active],mainTimbre:this.mainTimbre,volume:this.volume,reverb:this.reverb,audioState:this.ctx?.state||'closed'}}
    async renderComposition(pulse,targetDuration=30){
      const duration=targetDuration,sr=44100,OAC=global.OfflineAudioContext||global.webkitOfflineAudioContext;
      if(!OAC)throw Error('OfflineAudioContext unavailable');
      const perf=pulse.performanceProfile||{},cacheKey=JSON.stringify({engine:'through-composed-v2',duration,score:this.score?.scoreHash,active:pulse.activeInstruments||[...this.active],main:pulse.mainTimbre||this.mainTimbre,route:perf.routeOrder,dwell:perf.dwellByNode,speed:perf.speedBySegment,visits:perf.visitCountByNode,back:perf.reversalCount,complete:perf.completionRate,history:perf.historyDepthByNode});
      if(this.renderCache.has(cacheKey))return this.renderCache.get(cacheKey);
      const ctx=new OAC(2,sr*duration,sr),bus=makeBus(ctx,.9),rawOrder=perf.routeOrder?.length?perf.routeOrder:[0,1,2,3,4,5,6,7,8,9,10],order=rawOrder.filter((v,i)=>i===0||v!==rawOrder[i-1]),theme=this.themeMelody(),themeBeats=this.score?.themeBeats||48,usable=duration-1.05,selected=pulse.activeInstruments||[...this.active],segmentDuration=usable/order.length;
      if(!theme.length)throw Error('Theme score unavailable');
      order.forEach((idx,oi)=>{const p=this.profileForNode(idx),start=.02+oi*segmentDuration,end=Math.min(duration,start+segmentDuration+.28),root=p.act===3?48:43;drone(ctx,bus.input,root,start,Math.max(.2,end-start),.009+p.energy*.003,(p.act-2)*.045)});
      let lastSegment=-1;
      theme.forEach((base,j)=>{
        const progress=clamp(base.phraseBeat/themeBeats,0,.9999),oi=Math.min(order.length-1,Math.floor(progress*order.length)),idx=order[oi],p=this.profileForNode(idx),e=this.melodyForNode(idx)[j]||base,reversed=!!(oi&&idx<order[oi-1]),dwell=clamp((perf.dwellByNode?.[idx]||0)/8000,0,1),speed=clamp(perf.speedBySegment?.[idx]||.25,0,1.2),visits=perf.visitCountByNode?.[idx]||1,historyDepth=perf.historyDepthByNode?.[p.id]||0,lead=this.leadForNode(idx,selected),palette=this.paletteForNode(idx,selected),response=palette.find(id=>id!==lead&&id!=='drum'),beatSeconds=usable/themeBeats,t=.035+base.phraseBeat*beatSeconds,durationFactor=beatSeconds/.56*clamp(1.01-speed*.1+dwell*.16,.9,1.22),mod=(.7+dwell*.16+Math.min(2,visits-1)*.035)*(1-speed*.035);
        this.scheduleEvent(ctx,bus.input,e,t,lead,mod,{role:'lead',nodeIndex:idx,durationFactor,panReverse:reversed,harmony:e.phraseRole==='cadence'});
        if(oi!==lastSegment){
          lastSegment=oi;
          const accents={N11:'xiao',N10:'drum',N09:'pipa',N08:'sheng',N07:'pipa',N06:'bell',N05:'xiao',N04:'stone',N03:'qin',N02:'stone',N01:'qin'},accent=accents[p.id]||response||'qin',accentPitch=accent==='drum'?e.pitchMidi-24:e.pitchMidi-12;
          this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:accentPitch,harmony:[accentPitch],durationBeats:accent==='drum'?.3:Math.max(1,e.durationBeats),bassWeight:.08},t+.025,accent,.055+p.energy*.025,{role:'architecture',nodeIndex:idx,durationFactor:durationFactor*1.08,panReverse:reversed,bass:false});
          if(historyDepth>=2){const ritual=p.act===2?'bell':p.act===3?'xiao':'sheng',ritualPitch=e.pitchMidi-12;this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:ritualPitch,harmony:[ritualPitch],durationBeats:Math.max(1.2,e.durationBeats),bassWeight:.06},t+.12,ritual,.04+historyDepth*.012,{role:'history',nodeIndex:idx,durationFactor:durationFactor*1.14,bass:false})}
        }
        const stats=e.architectureControl||{},shadowHigh=stats.span>.72&&e.pitchMidi<=64,shadowPitch=shadowHigh?e.pitchMidi+12:e.pitchMidi-12;
        if(response&&(e.phraseRole==='cadence'||(stats.density>.7&&j%7===3)))this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:shadowPitch,harmony:[shadowPitch],bassWeight:.08},t+.045,response,.045+dwell*.025,{role:'shadow',nodeIndex:idx,durationFactor:durationFactor*1.06,panReverse:!reversed,bass:false});
        if(e.phraseRole==='opening'){
          const pedal={...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12],durationBeats:Math.max(2,e.durationBeats*2.2),bassWeight:.12};
          this.scheduleEvent(ctx,bus.input,pedal,t,p.act===3?'qin':'sheng',.07+p.energy*.035,{role:'pedal',nodeIndex:idx,durationFactor:durationFactor*1.25,bass:false});
          if(p.kind==='门')this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:e.pitchMidi-24,harmony:[e.pitchMidi-24],durationBeats:.28,bassWeight:.05},t,'drum',.1+p.energy*.04,{role:'gate',nodeIndex:idx,durationFactor:.66,panReverse:reversed,bass:false});
        }
        if(visits>1&&e.phraseRole==='answer')this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t+Math.min(.14,beatSeconds*.22),response||'qin',.04+Math.min(.04,(visits-1)*.015),{role:'echo',nodeIndex:idx,durationFactor:durationFactor*.82,panReverse:!reversed,bass:false});
        if(historyDepth>=2&&e.phraseRole==='cadence'){const ritual=p.act===2?'bell':p.act===3?'xiao':'sheng';this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:e.pitchMidi-12,harmony:[e.pitchMidi-12]},t+.08,ritual,.045+historyDepth*.018,{role:'history',nodeIndex:idx,durationFactor:durationFactor*1.12,bass:false})}
      });
      const lastIndex=order[order.length-1]??0,last=this.melodyForNode(lastIndex),complete=perf.completionRate??new Set(order).size/11;
      if(last.length){const e={...last[last.length-1],phraseRole:'cadence',harmony:[last[last.length-1].pitchMidi]},t=duration-1.02,lead=this.leadForNode(lastIndex,selected);this.scheduleEvent(ctx,bus.input,{...e,durationBeats:1.75,bassWeight:.62},t,lead,complete>=.8?.24:.16,{role:'final',durationFactor:1.25,harmony:false});this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:e.pitchMidi-12,durationBeats:2,bassWeight:.12},t+.035,'sheng',.085,{role:'final-pedal',durationFactor:1.25,bass:false})}
      const buffer=await ctx.startRendering();let peak=0,sum=0,count=0;
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++){const a=Math.abs(d[i]);peak=Math.max(peak,a);sum+=d[i]*d[i];count++}}
      const rms=Math.sqrt(sum/count)||1e-5,target=10**(this.p.mix.target_rms_dbfs/20),ceiling=10**(this.p.mix.peak_ceiling_dbfs/20),gain=Math.min(target/rms,ceiling/Math.max(peak,1e-5));
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]*=gain}
      const frame=Math.max(1,Math.round(sr*.05)),frames=Math.ceil(buffer.length/frame);let near=0,frameCount=0;
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let start=0;start<d.length;start+=frame){let power=0,n=0;for(let i=start;i<Math.min(d.length,start+frame);i++){power+=d[i]*d[i];n++}if(Math.sqrt(power/Math.max(1,n))<.0032)near++;frameCount++}}
      const result={buffer,stats:{duration,rmsDb:20*Math.log10(rms*gain),peakDb:20*Math.log10(peak*gain),nearSilenceRatio:near/frameCount,gain,silenceWindowMs:50}};this.renderCache.set(cacheKey,result);if(this.renderCache.size>3)this.renderCache.delete(this.renderCache.keys().next().value);return result
    }
    async renderThemeGuide(targetDuration=30,instrument='qin'){
      const duration=targetDuration,sr=44100,OAC=global.OfflineAudioContext||global.webkitOfflineAudioContext;if(!OAC)throw Error('OfflineAudioContext unavailable');
      const ctx=new OAC(2,sr*duration,sr),bus=makeBus(ctx,.9),theme=this.themeMelody(),beats=this.score?.themeBeats||48,usable=duration-.9,beatSeconds=usable/beats;
      theme.forEach(e=>this.scheduleEvent(ctx,bus.input,{...e,harmony:[e.pitchMidi],bassWeight:0},.04+e.phraseBeat*beatSeconds,instrument,.78,{role:'guide',durationFactor:beatSeconds/.56*.98,harmony:false,bass:false}));
      const buffer=await ctx.startRendering();let peak=0,sum=0,count=0;for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++){peak=Math.max(peak,Math.abs(d[i]));sum+=d[i]*d[i];count++}}
      const rms=Math.sqrt(sum/count)||1e-5,target=10**(-22/20),ceiling=10**(-2/20),gain=Math.min(target/rms,ceiling/Math.max(peak,1e-5));for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]*=gain}
      return{buffer,stats:{duration,rmsDb:20*Math.log10(rms*gain),peakDb:20*Math.log10(peak*gain),gain}}
    }
    async playBuffer(buffer,onEnded){await this.init();this.pause();const s=this.ctx.createBufferSource();s.buffer=buffer;s.connect(this.input);s.onended=onEnded;s.start();this.renderedSource=s}
  }
  global.AxisAudioEngine=AxisAudioEngine;
})(window);
