(function(global){
  'use strict';
  const utf8=s=>unescape(encodeURIComponent(s));
  const b64url=s=>btoa(utf8(s)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
  const from64=s=>decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(s.length/4)*4,'='))));
  function compact(p){const perf=p.performanceProfile||{},depth=perf.historyDepthByNode||{};return{v:5,id:p.pulseId,sv:p.scoreVersion,m:p.mode||'exhibition',r:p.route||'ceremony',n:p.nodes||[],t:p.mainTimbre||'qin',i:p.activeInstruments||[],d:(perf.dwellByNode||[]).map(v=>Math.min(255,Math.round(v/250))),s:(perf.speedBySegment||[]).map(v=>Math.min(255,Math.round(v*100))),sd:(perf.slowdownByNode||[]).map(v=>Math.min(100,Math.round(v*100))),vc:perf.visitCountByNode||[],o:perf.routeOrder||[],b:perf.reversalCount||0,c:Math.min(100,Math.round((perf.completionRate||0)*100)),hd:Object.entries(depth).map(([id,value])=>[Number(id.slice(1)),Math.min(3,Number(value)||0)]),rn:p.resonantNode,ps:p.performanceStyle,h:p.scoreHash,hm:p.historicalMatch?.id||null}}
  function expand(x){if(x.v===3)return{v:5,pulseId:x.id,scoreVersion:'0.5-legacy',mode:'exhibition',route:x.route||'ceremony',nodes:x.nodes||[],mainTimbre:(x.active||[])[0]||'qin',activeInstruments:x.active||[],performanceProfile:{dwellByNode:(x.dwell||[]).map(v=>v*250),speedBySegment:Array(11).fill((x.bpm||72)/150),slowdownByNode:Array(11).fill(0),visitCountByNode:Array(11).fill(0),routeOrder:(x.nodes||[]).map(id=>11-Number(id.slice(1))),reversalCount:x.backtracks||0,completionRate:0,historyDepthByNode:{}},resonantNode:null,performanceStyle:null,scoreHash:'legacy-'+(x.seed||0)};const historyDepthByNode=Object.fromEntries((x.hd||[]).map(([n,d])=>['N'+String(n).padStart(2,'0'),d]));return{v:5,pulseId:x.id,scoreVersion:x.sv,mode:x.m,route:x.r,nodes:x.n,mainTimbre:x.t,activeInstruments:x.i,performanceProfile:{dwellByNode:(x.d||[]).map(v=>v*250),speedBySegment:(x.s||[]).map(v=>v/100),slowdownByNode:(x.sd||[]).map(v=>v/100),visitCountByNode:x.vc||Array(11).fill(0),routeOrder:x.o||[],reversalCount:x.b||0,completionRate:(x.c||0)/100,historyDepthByNode,historyOpened:Object.keys(historyDepthByNode)},resonantNode:x.rn,performanceStyle:x.ps,scoreHash:x.h,historicalMatch:x.hm?{id:x.hm}:null}}
  function encode(pulse){return b64url(JSON.stringify(compact(pulse)))}
  function decode(payload){return expand(JSON.parse(from64(payload)))}
  function link(base,pulse){return base.replace(/#.*$/,'').replace(/\/$/,'/')+'#pulse='+encode(pulse)}
  function svg(url,size=164){if(typeof qrcode!=='function')return'';const qr=qrcode(0,'M');qr.addData(url,'Byte');qr.make();return qr.createSvgTag({cellSize:4,margin:2,scalable:true}).replace('<svg ',`<svg width="${size}" height="${size}" `)}
  global.AxisQR={compact,expand,encode,decode,link,svg};
})(window);
