(function(){
  'use strict';
  const $=id=>document.getElementById(id),json=id=>JSON.parse($(id).textContent);
  const initialHash=location.hash.slice(1),P=json('parameters'),historyNodes=json('history-data'),historyRoutes=json('routes-data'),sources=json('sources-data'),geoNodes=json('geo-data');
  const publicBase=(()=>{try{return location.protocol==='https:'?new URL('./',location.href).href.split(/[?#]/)[0]:P.nfc.public_base_url}catch(_){return P.nfc.public_base_url}})();
  const events=P.events.slice().sort((a,b)=>a.journey_order-b.journey_order),byId=Object.fromEntries(events.map((e,i)=>[e.id,{...e,index:i}])),features=P.features;
  const score=AxisScore.buildArchitectureScore({nodes:events,features,scoreConfig:P.score,scoreVersion:P.score.version}),perf=new AxisPerformance(events),historyEngine=new AxisHistory(historyNodes,sources,historyRoutes),collective=new AxisCollective(P.exhibition.local_storage_key),postcards=new AxisPostcards(P.postcards),artifacts=new AxisArtifacts(P);
  const engine=new AxisAudioEngine(P,syncAudio),state={current:0,hits:new Set(),view:'architecture',entered:false,experience:'exhibition',route:'ceremony',dragging:false,lastTrack:null,pulse:null,audio:null,artifact:'card',voice:null,postcard:null,pendingPulse:null,demo:false,historyDepth:0};
  engine.setScore(score);engine.setPerformance(perf);
  const storyTimer=setInterval(updateHistoryDepth,250);let toastTimer,demoTimer,wakeTimer,curatorIdleTimer,mediaRecorder,voiceStartedAt=0,voiceTicker,voiceChunks=[];
  const act=index=>index<=4?['ACT I · ENTER','入城 · 五门蓄势']:index<=7?['ACT II · CEREMONY','外朝 · 礼制回响']:['ACT III · INNER COURT','内廷 · 近场余韵'];
  const featureAt=x=>features.reduce((best,f)=>Math.abs(f.x-x)<Math.abs(best.x-x)?f:best,features[0]);
  const nodeName=id=>byId[id]?.label||id;
  const open=(id,on=true)=>{const el=$(id);el.classList.toggle('open',on);el.setAttribute('aria-hidden',String(!on));el.inert=!on};
  function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
  function wav(buffer){const ch=buffer.numberOfChannels,len=buffer.length*ch*2,out=new ArrayBuffer(44+len),v=new DataView(out),w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+len,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,ch,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*ch*2,true);v.setUint16(32,ch*2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len,true);let o=44;for(let i=0;i<buffer.length;i++)for(let c=0;c<ch;c++){const s=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([out],{type:'audio/wav'})}

  function build(){
    $('scoreCount').textContent=score.events.length;$('scoreHash').textContent=score.scoreHash;
    $('nodeLayer').innerHTML=events.map(e=>`<button class="axis-node" data-node="${e.id}" style="left:${5+e.x*90}%" aria-label="${e.label}" title="${e.label}">${e.label}</button>`).join('');
    $('chapterProgress').innerHTML=events.map(()=>'<span></span>').join('');
    $('instrumentGrid').innerHTML=P.instruments.map(i=>`<div class="instrument" data-inst="${i.id}" style="--inst:${i.color}"><button data-toggle="${i.id}" aria-label="启停${i.label}">${i.glyph}</button><div><b>${i.label}</b><small>${i.family} · ${i.en}</small></div><button class="ear" data-preview="${i.id}" aria-label="试听${i.label}">耳</button></div>`).join('');
    $('atlasGrid').innerHTML=events.map(e=>`<button data-atlas="${e.id}"><img src="${P.media[e.id].photo}" alt="${e.label}"><span>${e.id} · ${e.label}</span></button>`).join('');
    const options=events.map(e=>`<option value="${e.id}">${e.label}</option>`).join('');$('studyA').innerHTML=options;$('studyB').innerHTML=options;$('studyA').value='N08';$('studyB').value='N05';
    $('walkNodes').innerHTML=events.map((e,i)=>`<li data-walk="${e.id}"><span>${e.label}</span><button data-arrive="${e.id}">确认到达</button></li>`).join('');
    $('artifactTypes').innerHTML=[['card','京声卡'],['postcard','同路明信片'],['ticket','京声票'],['foldout','声谱折页'],['bookmark','书签'],['ruler','一尺中轴'],['journal','中轴行志'],['overlay','京声叠影']].map(([id,n],i)=>`<button data-artifact="${id}" class="${i?'':'active'}">${n}</button>`).join('');
    document.querySelectorAll('[aria-hidden="true"]').forEach(el=>el.inert=true);selectNode(0,false);drawStudy('A');drawStudy('B');syncAudio();syncTrace();showToday();renderCollection();
  }

  async function enter(){if(state.entered)return;state.entered=true;$('cover').inert=true;try{await engine.init();await engine.intro();toast('声音已开启')}catch(e){$('soundStatus').querySelector('b').textContent='静音浏览';toast('声音未开启，视觉交互仍可使用')}$('cover').classList.add('hidden');startWake()}
  function startWake(){$('awakening').classList.add('open');$('awakening').setAttribute('aria-hidden','false');const steps=[...document.querySelectorAll('.wake-steps b')];let i=0;wakeTimer=setInterval(()=>{steps.forEach((s,n)=>s.classList.toggle('active',n<=i));i++;if(i>=steps.length){clearInterval(wakeTimer);setTimeout(endWake,450)}},820)}
  function endWake(){clearInterval(wakeTimer);$('awakening').classList.remove('open');$('awakening').setAttribute('aria-hidden','true');$('awakening').inert=true;const query=new URLSearchParams(location.search);if(query.has('study'))document.body.classList.add('advanced-mode','study-mode');if(query.get('mode')==='curator')document.body.classList.add('advanced-mode','curator-mode');if(state.pendingPulse){startExperience('exhibition');restore(state.pendingPulse)}else if(query.has('study')){startExperience('exhibition');open('studyModal')}else if(query.get('mode')==='curator'){startExperience('exhibition');open('todayModal');showToday(true);armCuratorIdle()}else open('entryChoice')}
  async function startExperience(type){state.experience=type;open('entryChoice',false);$('app').classList.add('ready');$('app').setAttribute('aria-hidden','false');$('app').inert=false;selectNode(state.current,false);await engine.start();if(type==='walk')open('walkModal');toast(type==='walk'?'实地模式已准备，可开启定位或手动到达':'建筑谱已开始演奏')}
  function armCuratorIdle(){clearTimeout(curatorIdleTimer);curatorIdleTimer=setTimeout(()=>{walk.stop();engine.pause();document.querySelectorAll('.open').forEach(el=>open(el.id,false));$('app').classList.remove('ready');$('app').setAttribute('aria-hidden','true');$('app').inert=true;$('cover').classList.remove('hidden');$('cover').inert=false;state.entered=false;toast('策展模式已回到封面')},90000)}

  function selectNode(index,user=true,source='screen'){
    index=Math.max(0,Math.min(10,index));const e=events[index],f=featureAt(e.x),h=historyEngine.enter(e.id),a=act(index);state.current=index;state.historyDepth=0;
    if(user){perf.enterNode(index,e.x,source);state.hits.add(index)}
    engine.setSemantic(historyEngine.semantic(e.id));engine.setNode(e,index);
    $('nodeCode').textContent=`${e.id} · ${e.kind==='门'?'GATE':'HALL'}`;$('nodeName').textContent=e.label;$('nodeEn').textContent=e.label_en.toUpperCase();$('nodeStory').textContent=h?.story||'建筑结构正在转化为节奏与空间。';$('actCode').textContent=a[0];$('actName').textContent=a[1];$('motifName').textContent='《茉莉花》建筑声部 · '+(P.score.node_motifs?.[e.id]?.name||e.label);
    $('geoPosition').textContent=e.x.toFixed(2);$('geoDensity').textContent=f.density.toFixed(2);$('geoEnclosure').textContent=f.enclosure.toFixed(2);$('geoSpan').textContent=f.span.toFixed(2);$('scanLine').style.left=(5+e.x*90)+'%';$('buildingImage').src=P.media[e.id].photo;$('buildingImage').alt=e.label+'实景或团队重建';$('imageCredit').textContent=P.media[e.id].credit;
    $('wipeArchive').src=P.media[e.id].drawing;$('wipeToday').src=P.media[e.id].photo;renderTimeline(e.id);
    document.querySelectorAll('.axis-node').forEach((n,i)=>{n.classList.toggle('active',i===index);n.classList.toggle('hit',state.hits.has(i))});
    drawScore();syncTrace();renderRitualScene(e.id,source==='demo'?3:1,0);$('transportTitle').textContent=e.label+' · 建筑谱';updateHistoryDepth();if(state.entered)history.replaceState(null,'','#route='+state.route+'&node='+e.id)
  }
  function syncTrace(){const p=perf.snapshot(),order=p.routeOrder;$('hitCount').textContent=state.hits.size+' / 11';$('traceList').innerHTML=order.length?order.slice(-12).map(i=>`<span>${events[i].label}</span>`).join(''):'<span>等待你的第一步</span>';$('reversalCount').textContent=p.reversalCount;$('completion').textContent=Math.round(p.completionRate*100)+'%';$('stylePreview').textContent=order.length?p.performanceStyle:'等待行走';const ok=state.hits.size>=3;$('generateBtn').disabled=$('finishBtn').disabled=!ok;$('generateHint').textContent=ok?'建筑、历史与行走将合卷成曲':'至少经过 3 个建筑';document.querySelectorAll('.chapter-progress span').forEach((s,i)=>s.classList.toggle('done',state.hits.has(i)))}
  function renderRitualScene(id,depth,elapsed){const scene=$('ritualScene'),year=new Date().getFullYear();scene.classList.remove('active','taihe','baohe','jiaotai','kunning');if(depth<2)return;const copy={N06:['taihe','元旦大朝 · 礼乐高潮','今日听见的是建筑几何与礼制史料共同触发的当代声化创作。',['皇帝驻中和殿','中和韶乐引导','太和殿受朝']],N04:['baohe','殿试传胪 · 三音越门','保和殿发榜、太和门候传、午门出宫，三处建筑把同一礼序接成回声。',['保和殿','太和门','午门']],N02:['jiaotai','历史时间 → 我的时间','滴漏与自鸣钟曾标记宫廷时间；此刻脉冲正在跟随你的停留。',[`停留 ${(elapsed/1000).toFixed(1)} 秒`,'时间脉冲','我的京声']],N01:['kunning','婚成礼 · 合卺回声',`${year-1665} 年之后，你在坤宁宫续写一段当代停留。`,['1665','1870',String(year)]]}[id];if(!copy)return;scene.classList.add('active',copy[0]);$('ritualTitle').textContent=copy[1];$('ritualCopy').textContent=copy[2];$('ritualLines').innerHTML=copy[3].map((x,i)=>`<span style="--delay:${i*.16}s">${x}</span>`).join('')}
  function updateHistoryDepth(){if(!state.entered)return;const elapsed=performance.now()-historyEngine.enteredAt,h=historyEngine.view(events[state.current].id,elapsed);if(!h)return;$('historyDepth').textContent=h.depth===1?'一眼':h.depth===2?'一段曾经':'历史回声';$('historyText').textContent=h.text;$('dwellNow').textContent=(elapsed/1000).toFixed(1)+'s';renderRitualScene(h.nodeId,h.depth,elapsed);if(h.depth>state.historyDepth){state.historyDepth=h.depth;if(h.depth>=2){perf.markHistory(h.nodeId,h.depth);engine.playHistory(h.nodeId,h.depth);drawScore()}}}
  function renderTimeline(id){const years={N11:[['1420','大明门建成'],['1644','清代改称大清门'],['1870','图档记录'],['TODAY','旧址与缺席']],N08:[['1870','图档记录'],['TODAY','紫禁城正门']],N06:[['1870','图档记录'],['TODAY','外朝礼仪峰值']],N04:[['1789','殿试固定于保和殿'],['1870','图档记录'],['TODAY','建筑仍存']],N02:[['1870','滴漏与自鸣钟的历史时间'],['TODAY','我的时间']],N01:[['1665','康熙大婚合卺礼'],['1870','图档记录'],['TODAY',`${new Date().getFullYear()-1665}年后`]]}[id]||[['1870','图档记录'],['TODAY','今日建筑']];$('timeline').innerHTML=years.map(([y,t],i)=>`<button class="${i?'':'active'}" data-year="${y}" data-copy="${t}" title="点击查看 ${t}"><b>${y}</b><small>${t}</small></button>`).join('');showTimePoint($('timeline').querySelector('button'))}
  function showTimePoint(button){if(!button)return;document.querySelectorAll('#timeline button').forEach(b=>b.classList.toggle('active',b===button));$('timeYear').textContent=button.dataset.year;$('timeCopy').textContent=button.dataset.copy}

  function setView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('mediaFrame').className='media-frame '+(view==='score'?'score':view==='time'?'time':'');$('imageCredit').textContent=view==='score'?'真实 scoreEvents · 与实际音频同源':view==='time'?'团队重绘图档与开放授权今日影像':P.media[events[state.current].id].credit}
  function drawScore(canvas=$('scoreCanvas'),nodeOnly=false,nodeId=events[state.current].id){const x=canvas.getContext('2d'),w=canvas.width,h=canvas.height;x.clearRect(0,0,w,h);x.fillStyle='#fbf3e3';x.fillRect(0,0,w,h);x.strokeStyle='rgba(66,48,30,.12)';for(let y=110;y<h-55;y+=72){x.beginPath();x.moveTo(55,y);x.lineTo(w-45,y);x.stroke()}const src=nodeOnly?score.events.filter(e=>e.nodeId===nodeId):score.events,lo=Math.min(...score.events.map(e=>e.pitchMidi)),hi=Math.max(...score.events.map(e=>e.pitchMidi));src.forEach((e,i)=>{if(!nodeOnly&&i%2)return;const px=w-55-e.timeNorm*(w-110),py=h-70-(e.pitchMidi-lo)/Math.max(1,hi-lo)*(h-170),active=e.nodeId===events[state.current].id;x.globalAlpha=active?1:.2;x.strokeStyle=active?'#a63b31':'#40372f';x.fillStyle=active?'#a63b31':'#40372f';x.lineWidth=Math.max(1,e.velocity*4);if(e.timbreRole==='threshold_transient'){x.beginPath();x.moveTo(px,py-16);x.lineTo(px,py+16);x.stroke()}else{x.beginPath();x.arc(px,py,2+e.velocity*5,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(px,py);x.lineTo(px+Math.min(42,e.durationBeats*16),py);x.stroke()}if(active&&state.historyDepth>=2){x.globalAlpha=.7;x.fillStyle='#b38a36';x.beginPath();x.arc(px+5,py+10,2+e.velocity*3,0,Math.PI*2);x.fill()}});x.globalAlpha=1;x.fillStyle='#211b16';x.font='38px serif';x.fillText((nodeOnly?nodeName(nodeId):'大清门 → 坤宁宫')+' · 建筑乐谱',55,65);x.font='16px Arial';x.fillStyle='#6d6154';x.fillText(`SCORE ${score.scoreVersion} · ${score.scoreHash} · X=中轴/时间 · Y=音高`,55,h-28)}
  function drawStudy(which){const id=$(which==='A'?'studyA':'studyB').value,canvas=$(which==='A'?'studyCanvasA':'studyCanvasB');drawScore(canvas,true,id)}
  function sourceLinks(ids=[]){const offline=!navigator.onLine,rows=ids.map(id=>sources.find(s=>s.id===id)).filter(Boolean);return`${offline?'<p class="offline-note">当前离线：来源名称仍可核验，外链将在联网后打开。</p>':''}${rows.map(s=>`<div class="proof-source"><b>${s.institution}</b><span>${s.title}</span><a href="${s.url}" target="_blank" rel="noopener">${s.url}</a></div>`).join('')}`}
  function showProof(){const h=historyEngine.view(events[state.current].id,9000);if(!h)return toast('该条目尚无可公开核验来源');$('proofTitle').textContent=h.oneLook;$('proofContent').innerHTML=`<p class="truth-badge">${h.truthLevel}</p><p>${h.historyEcho||h.story}</p>${sourceLinks(h.sourceIds)}<p><b>声音说明：</b>历史声部属于当代策展转译，并非史实或历史乐曲复原。</p>`;open('proofDrawer')}
  function showMatchProof(){const m=state.pulse?.historicalMatch;if(!m||m.type==='none')return toast('这次路线保持为自由演奏，没有强行匹配历史');$('proofTitle').textContent=(m.type==='route'?'与你同路 · ':'与你同场 · ')+m.label;$('proofContent').innerHTML=`<p class="truth-badge">${m.truthLevel}</p><p>${m.explanation||''}</p>${sourceLinks(m.sourceIds)}<p><b>声音说明：</b>路线与场景来自制度史料；三音动机、配器和余响是团队策展转译，并非历史乐曲复原。</p>`;open('proofDrawer')}
  function renderMatch(m){if(!m||m.type==='none'){$('matchTrail').innerHTML='<p>你的路线更接近一次自由演奏。</p>';$('resultProof').hidden=true;return}$('resultProof').hidden=false;$('matchTrail').innerHTML=(m.nodes||[]).map(n=>n?.gap?`<span class="gap">⋯<small>${n.label}</small>⋯</span>`:`<span class="${(m.matchedNodes||[]).includes(n)?'matched':''}">${nodeName(n)}</span>`).join('<i>→</i>')+`<p>${m.explanation||''}</p>`}

  function renderCollection(reveal){const s=postcards.summary();$('collectionCount').textContent=`${s.count}/${s.total}`;$('collectionGrid').innerHTML=P.postcards.items.map((item,i)=>{const unlocked=s.unlocked.includes(item.id);return`<article class="collection-item ${unlocked?'unlocked':'locked'}" style="--card-accent:${item.accent}"><div>${unlocked?`<img src="${item.image}" alt="${item.title}紫禁城原创手绘">`:'<span>待<br>相遇</span>'}<b>${String(i+1).padStart(2,'0')}</b></div><h3>${unlocked?item.title:'未收录的宫阙光景'}</h3><p>${unlocked?item.season:'完成一首新的京声'}</p></article>`}).join('');$('postcardArtistNote').textContent=P.postcards.artist_note;$('scrollReward').hidden=!s.complete;if(s.complete){$('rewardImage').src=s.reward.image;$('rewardTitle').textContent=s.reward.title;$('downloadReward').href=s.reward.image}if(reveal){$('postcardReveal').hidden=false;$('postcardHero').src=reveal.item.image;$('postcardTitle').textContent=reveal.item.title;$('postcardNumber').textContent=`${reveal.item.id} / ${String(s.total).padStart(2,'0')}`;$('postcardMessage').textContent=reveal.isNew?'这是一张新光景，已经盖入你的本机集卡册。':'这段京声曾抽中过它；同一首歌永远对应同一张明信片。'}}
  function imageData(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);resolve(c.toDataURL('image/jpeg',.9))};img.onerror=reject;img.src=src})}
  async function drawPostcard(){if(!state.pulse)return toast('请先完成一首《我的京声》');const draw=postcards.draw(state.pulse.pulseId);state.postcard=draw.item;state.pulse.postcard=draw.item;try{state.pulse.postcardDataUrl=await imageData(draw.item.image)}catch(_){state.pulse.postcardDataUrl=draw.item.image}renderCollection(draw);$('postcardMessage').textContent+=(state.pulse.voiceSeal?.length?' 你的声音落款也已盖入可打印明信片。':' 你还可以返回结果页录一句京声，再把声纹盖入明信片。');$('drawPostcard').innerHTML=`<b>已抽中 · ${draw.item.title}</b><small>${state.pulse.voiceSeal?.length?'声音落款已入明信片':'可返回录一句京声并盖入卡面'}</small>`;open('resultModal',false);open('postcardModal');toast(state.pulse.voiceSeal?.length?'宫阙光景与声音落款已经合印':'明信片已抽取；录一句京声还能加盖声音落款')}

  function pointerRatio(e){const r=$('axisTrack').getBoundingClientRect(),visual=(e.clientX-r.left)/r.width;return Math.max(0,Math.min(1,(visual-.05)/.9))}
  function playTrack(e){const pos=pointerRatio(e);perf.record(pos,performance.now(),'screen');const sp=perf.speedSamples.at(-1)||.25;engine.setTempoFactor(.82+Math.min(1.2,sp)*.38);if(state.lastTrack!==null){const lo=Math.min(state.lastTrack,pos),hi=Math.max(state.lastTrack,pos),crossed=events.map((n,i)=>({n,i})).filter(o=>o.n.x>=lo&&o.n.x<=hi).sort((a,b)=>pos>=state.lastTrack?a.n.x-b.n.x:b.n.x-a.n.x);crossed.forEach(o=>selectNode(o.i,true))}const idx=events.reduce((best,n,i)=>Math.abs(n.x-pos)<Math.abs(events[best].x-pos)?i:best,0);if(idx!==state.current)selectNode(idx,true);state.lastTrack=pos}
  async function demo(){if(state.demo)return;state.demo=true;state.route='ceremony';reset(false);await engine.restart();let i=0;selectNode(0,true,'demo');demoTimer=setInterval(()=>{i++;if(i>=11){clearInterval(demoTimer);state.demo=false;toast('十一章已经奏完，正在合卷成曲');setTimeout(()=>generate(),320);return}selectNode(i,true,'demo')},1000);toast('演示开始 · 十二秒听遍中轴')}
  function reset(show=true){clearInterval(demoTimer);clearInterval(voiceTicker);state.demo=false;state.hits.clear();state.voice=null;if(state.pulse)delete state.pulse.voiceSeal;const vc=$('voiceCanvas');vc?.getContext('2d').clearRect(0,0,vc.width,vc.height);document.querySelector('.voice-seal')?.classList.remove('recording','ready');if($('voiceStatus'))$('voiceStatus').textContent='等待声音落款';if($('recordVoice'))$('recordVoice').textContent='● 开始录制';if($('playVoice'))$('playVoice').disabled=true;if($('deleteVoice'))$('deleteVoice').disabled=true;perf.reset();engine.setPerformance(perf);selectNode(0,false);syncTrace();if(show)toast('已回到大清门，等待重新演奏')}

  function pulseData(base){if(base)return base;const profile=perf.snapshot(),ids=profile.routeOrder.map(i=>events[i].id),core={v:5,scoreVersion:score.scoreVersion,mode:state.experience,route:state.route,nodes:ids,mainTimbre:engine.mainTimbre,activeInstruments:[...engine.active],performanceProfile:profile,resonantNode:profile.resonantNode,performanceStyle:profile.performanceStyle,scoreHash:score.scoreHash};const historicalMatch=historyEngine.match(profile),pulseId='AP-'+AxisScore.stableHash({...core,historicalMatch}).toUpperCase();return{...core,pulseId,historicalMatch,axisTrace:profile.routeOrder,sonicWave:[],audioStats:{},createdAtLocal:new Date().toISOString()}}
  function waveFrom(buffer,n=620){const d=buffer.getChannelData(0),step=Math.max(1,Math.floor(d.length/n)),a=[];for(let i=0;i<n;i++){let peak=0,sign=1;for(let j=0;j<step;j++){const v=d[i*step+j]||0;if(Math.abs(v)>peak){peak=Math.abs(v);sign=Math.sign(v)||1}}a.push(peak*sign)}return a}
  async function generate(base){if(!base&&state.hits.size<3)return;open('resultModal');$('resultLead').textContent='建筑谱、历史声部与行走正在合卷…';const pulse=pulseData(base);engine.setPerformance(pulse.performanceProfile);try{const audio=await engine.renderComposition(pulse);pulse.sonicWave=waveFrom(audio.buffer);pulse.audioStats=audio.stats;if(state.voice)pulse.voiceSeal=waveFrom(state.voice,180);const nodeMedia=P.media[pulse.resonantNode];if(nodeMedia){pulse.resonantMediaCredit=nodeMedia.credit;try{pulse.resonantImageDataUrl=await imageData(nodeMedia.photo)}catch(_){pulse.resonantImageDataUrl=nodeMedia.photo}}state.pulse=pulse;state.audio=audio;const saved=postcards.getForPulse(pulse.pulseId);if(saved){state.postcard=saved;pulse.postcard=saved;try{pulse.postcardDataUrl=await imageData(saved.image)}catch(_){pulse.postcardDataUrl=saved.image}}await renderResult();const m=pulse.historicalMatch||{type:'none',label:'自由演奏'},match=m.type==='route'?'与你同路 · '+m.label:m.type==='scene'?'与你同场 · '+m.label:'自由演奏';$('resultResonant').textContent=nodeName(pulse.resonantNode);$('resultStyle').textContent=pulse.performanceStyle||'徐行';$('resultMatch').textContent=match;$('resultNodes').textContent=`${new Set(pulse.nodes).size} / 11`;renderMatch(m);const missing=Math.max(0,11-new Set(pulse.nodes).size),walkResult=missing<=1?'步步成章':`未竟 ${missing} 章`;$('resultLead').textContent=`${pulse.pulseId} · ${pulse.mode==='walk'?walkResult:'展厅演奏'}`;$('drawPostcard').innerHTML=saved?`<b>已抽中 · ${saved.title}</b><small>${pulse.voiceSeal?.length?'声音落款已入明信片':'点击查看集卡册'}</small>`:'<b>抽取本次京声明信片</b><small>六款原创宫阙手绘 · 可加盖声音落款</small>';$('audioStats').textContent=`30.0 s · RMS ${audio.stats.rmsDb.toFixed(1)} dBFS · Peak ${audio.stats.peakDb.toFixed(1)} dBFS · 近静音 ${(audio.stats.nearSilenceRatio*100).toFixed(1)}%`;toast('你的中轴已经成曲')}catch(e){$('resultLead').textContent='成曲遇到问题：'+e.message;console.error(e)}}
  async function renderResult(){const url=AxisQR.link(publicBase,state.pulse),svg=artifacts.render('card',state.pulse,{url}),blob=new Blob([svg],{type:'image/svg+xml'}),src=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=src});const c=$('resultCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(src)}
  function openArtifact(type=state.artifact){if(!state.pulse)return;state.artifact=type;document.body.dataset.printArtifact=type;document.querySelectorAll('[data-artifact]').forEach(b=>b.classList.toggle('active',b.dataset.artifact===type));const url=AxisQR.link(publicBase,state.pulse);$('artifactPreview').innerHTML=artifacts.render(type,state.pulse,{url});open('resultModal',false);open('artifactModal')}
  async function restore(pulse){state.pendingPulse=null;state.pulse=pulse;const profile=pulse.performanceProfile||{};perf.reset();Object.assign(perf,{dwellByNode:profile.dwellByNode||Array(11).fill(0),visitCountByNode:profile.visitCountByNode||Array(11).fill(0),slowdownByNode:profile.slowdownByNode||Array(11).fill(0),speedBySegment:profile.speedBySegment||Array(11).fill(0),routeOrder:profile.routeOrder||[],reversalCount:profile.reversalCount||0,historyOpened:profile.historyOpened||[],historyDepthByNode:profile.historyDepthByNode||{}});state.hits=new Set(perf.routeOrder);engine.setEnsemble(pulse.activeInstruments||['qin','xiao','sheng']);engine.setMainTimbre(pulse.mainTimbre||'qin');const restoredProfile=perf.snapshot();pulse.performanceProfile={...restoredProfile,...profile};pulse.resonantNode=pulse.resonantNode||restoredProfile.resonantNode;pulse.performanceStyle=pulse.performanceStyle||restoredProfile.performanceStyle;if(pulse.historicalMatch?.id){const r=historyRoutes.find(x=>x.id===pulse.historicalMatch.id),matched=(r?.nodes||[]).filter(n=>typeof n==='string'&&pulse.nodes.includes(n));pulse.historicalMatch={...pulse.historicalMatch,type:r?.type.includes('route')?'route':'scene',label:r?.label||pulse.historicalMatch.id,truthLevel:r?.truthLevel,sourceIds:r?.sourceIds||[],nodes:r?.nodes||[],matchedNodes:matched,explanation:r?.type.includes('route')?`你经过的 ${matched.map(nodeName).join('、')} 与这条历史礼序重合。`:`你的共鸣建筑落在“${r?.label}”发生的空间。`}}else pulse.historicalMatch=historyEngine.match(restoredProfile);syncTrace();await generate(pulse);toast('欢迎回来，这是你的京声。')}

  const walk=new AxisWalk(geoNodes,{onFallback:m=>$('walkStatus').textContent=m,onApproach:(n,d)=>$('walkStatus').textContent=n?`APPROACHING ${nodeName(n.nodeId)} · 约 ${Math.round(d)}m`:'尚未进入已核验节点范围',onRhythm:r=>{if(r.speed)engine.setTempoFactor(.8+Math.min(1.2,r.speed/2)*.4)},onArrived:(id,source)=>{const i=byId[id].index;document.querySelector(`[data-walk="${id}"]`)?.classList.add('done');selectNode(i,true,'walk');$('walkStatus').textContent=`ARRIVED · ${nodeName(id)} · ${source==='gps'?'位置与停留判定':'手动确认'}`}});walk.setRoute(events.map(e=>e.id));
  function showToday(curator=false){const s=collective.summary(),name=nodeName(s.resonantNode);$('todaySummary').innerHTML=`<div><b>${s.count}</b><span>今日匿名京声</span></div><div><b>${name||'—'}</b><span>停留最多建筑</span></div><div><b>${s.averageDurationMs?Math.round(s.averageDurationMs/1000)+'s':'—'}</b><span>平均体验时长</span></div>${curator?`<div><b>${s.topTimbre||'—'}</b><span>最常选主奏</span></div><div><b>${Math.round(s.historyOpenRate*100)}%</b><span>历史打开率</span></div>`:''}`;const c=$('todayCanvas'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle='#fffaf0';x.fillRect(0,0,w,h);s.traces.forEach((tr,k)=>{x.strokeStyle=`rgba(24,115,140,${Math.min(.38,.08+k*.025)})`;x.beginPath();tr.forEach((v,i)=>{const px=50+i/10*(w-100),py=h-45-v*(h-90);if(!i)x.moveTo(px,py);else x.lineTo(px,py)});x.stroke()});x.fillStyle='#a63b31';x.font='26px serif';x.fillText(`${s.date} · ${s.count} 条匿名行走谱`,48,38)}
  async function playToday(){const s=collective.summary();if(!s.count){toast('今天还没有匿名京声样本');return}const avg=Array(11).fill(0);s.traces.forEach(t=>t.forEach((v,i)=>avg[i]+=v/s.count));const profile={dwellByNode:avg.map(v=>v*6000),visitCountByNode:Array(11).fill(1),slowdownByNode:avg,speedBySegment:Array(11).fill(.28),routeOrder:[0,1,2,3,4,5,6,7,8,9,10],reversalCount:0};toast('正在汇聚今日匿名声部');const audio=await engine.renderComposition({activeInstruments:['qin','xiao','sheng','bell'],performanceProfile:profile},60);engine.playBuffer(audio.buffer,()=>toast('今日京声试听结束'))}

  async function toggleVoice(){
    if(mediaRecorder?.state==='recording'){if(performance.now()-voiceStartedAt<1900){toast('请至少说满 2 秒，让声纹更完整');return}mediaRecorder.stop();return}
    if(!navigator.mediaDevices?.getUserMedia){toast('此浏览器不支持录音，其他体验仍可使用');return}
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});voiceChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>voiceChunks.push(e.data);mediaRecorder.onstop=async()=>{clearInterval(voiceTicker);stream.getTracks().forEach(t=>t.stop());document.querySelector('.voice-seal')?.classList.remove('recording');const blob=new Blob(voiceChunks,{type:mediaRecorder.mimeType}),arr=await blob.arrayBuffer();state.voice=await engine.ctx.decodeAudioData(arr.slice(0));drawVoice(state.voice);if(state.pulse){state.pulse.voiceSeal=waveFrom(state.voice,180);await renderResult()}document.querySelector('.voice-seal')?.classList.add('ready');$('voiceStatus').textContent='声音落款已完成';$('deleteVoice').disabled=false;$('playVoice').disabled=false;$('recordVoice').textContent='重新录制';toast('真实声纹已盖入结果卡与明信片，只保留在当前内存')};mediaRecorder.start();voiceStartedAt=performance.now();document.querySelector('.voice-seal')?.classList.add('recording');document.querySelector('.voice-seal')?.classList.remove('ready');$('recordVoice').textContent='■ 完成落款';$('voiceStatus').textContent='正在收录 0.0 / 5.0 秒';voiceTicker=setInterval(()=>{const elapsed=Math.min(5,(performance.now()-voiceStartedAt)/1000);$('voiceStatus').textContent=`正在收录 ${elapsed.toFixed(1)} / 5.0 秒`;if(elapsed>=5&&mediaRecorder?.state==='recording')mediaRecorder.stop()},100)}catch(_){document.querySelector('.voice-seal').hidden=true;toast('麦克风未授权，主体验、成曲和明信片仍可完整使用')}}
  function drawVoice(buffer){const c=$('voiceCanvas'),x=c.getContext('2d'),d=buffer.getChannelData(0);x.clearRect(0,0,c.width,c.height);x.strokeStyle='#a63b31';x.beginPath();for(let i=0;i<c.width;i++){const v=d[Math.floor(i/c.width*d.length)]||0,py=c.height/2-v*c.height*.42;if(!i)x.moveTo(i,py);else x.lineTo(i,py)}x.stroke()}
  function syncAudio(s=engine.snapshot()){if(!$('playBtn'))return;$('playBtn').textContent=s.playing?'Ⅱ':'▶';$('playState').textContent=s.playing?'正在实时演奏':'音乐已暂停';$('barCount').textContent=String(Math.max(1,(s.bar||1)%99)).padStart(2,'0');$('voiceCount').textContent=s.active.length+' / 4 声部';document.querySelectorAll('.instrument').forEach(c=>c.classList.toggle('active',s.active.includes(c.dataset.inst)))}
  function liveWave(){const c=$('liveWave'),x=c.getContext('2d'),a=new Uint8Array(512);engine.waveform(a);x.clearRect(0,0,c.width,c.height);x.strokeStyle=engine.playing?'#e6bd67':'rgba(255,255,255,.35)';x.lineWidth=2;x.beginPath();a.forEach((v,i)=>{const px=i/(a.length-1)*c.width,py=v/255*c.height;if(!i)x.moveTo(px,py);else x.lineTo(px,py)});x.stroke();requestAnimationFrame(liveWave)}

  build();liveWave();
  window.AxisPulseDebug={score,performance:perf,history:historyEngine,postcards,audio:engine,state,pulseData,generate,drawPostcard,version:P.score.version};
  $('enterBtn').addEventListener('click',enter);$('skipWake').addEventListener('click',endWake);document.querySelectorAll('[data-experience]').forEach(b=>b.addEventListener('click',()=>startExperience(b.dataset.experience)));$('homeBtn').addEventListener('click',()=>open('entryChoice'));$('archiveBtn').addEventListener('click',()=>open('archiveDrawer'));$('collectionBtn').addEventListener('click',()=>{renderCollection();open('postcardModal')});$('studyBtn').addEventListener('click',()=>open('studyModal'));$('todayBtn').addEventListener('click',()=>{showToday();open('todayModal')});$('aboutBtn').addEventListener('click',()=>open('aboutModal'));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.close==='walkModal')walk.stop();open(b.dataset.close,false)}));
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel-view]').forEach(x=>x.classList.toggle('active',x.dataset.panelView===b.dataset.panel))}));
  $('nodeLayer').addEventListener('click',e=>{const b=e.target.closest('[data-node]');if(b)selectNode(byId[b.dataset.node].index,true)});$('atlasGrid').addEventListener('click',e=>{const b=e.target.closest('[data-atlas]');if(b){selectNode(byId[b.dataset.atlas].index,true);open('archiveDrawer',false)}});$('instrumentGrid').addEventListener('click',e=>{const p=e.target.closest('[data-preview]'),t=e.target.closest('[data-toggle]');if(p){engine.preview(p.dataset.preview);return}if(t&&!engine.toggleInstrument(t.dataset.toggle))toast('最多同时开启四个声部')});document.querySelectorAll('[data-family]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-family]').forEach(x=>x.classList.toggle('active',x===b));const map={silk:'qin',bamboo:'xiao',ritual:'bell'};engine.setMainTimbre(map[b.dataset.family]);toast('主奏已切换为'+P.instruments.find(i=>i.id===map[b.dataset.family]).label)}));document.querySelectorAll('[data-route-mode]').forEach(b=>b.addEventListener('click',()=>{state.route=b.dataset.routeMode;document.querySelectorAll('[data-route-mode]').forEach(x=>x.classList.toggle('active',x===b));toast(state.route==='ceremony'?'礼序演奏：默认南→北':'自由演奏：顺序由你决定')}));
  $('playBtn').addEventListener('click',()=>engine.playing?engine.pause():engine.start());$('themeBtn').addEventListener('click',()=>{engine.previewTheme();toast('正在试听八拍母谱；点击建筑可听轻微变调')});$('demoBtn').addEventListener('click',demo);$('resetBtn').addEventListener('click',()=>reset());$('reverbRange').addEventListener('input',e=>{engine.setReverb(e.target.value/100);$('reverbText').textContent=e.target.value+'%'});$('volumeRange').addEventListener('input',e=>{engine.setVolume(e.target.value/100);$('volumeText').textContent=e.target.value+'%'});
  $('axisTrack').addEventListener('pointerdown',e=>{state.dragging=true;state.lastTrack=pointerRatio(e);$('axisTrack').setPointerCapture(e.pointerId);playTrack(e)});$('axisTrack').addEventListener('pointermove',e=>{if(state.dragging)playTrack(e)});['pointerup','pointercancel'].forEach(k=>$('axisTrack').addEventListener(k,()=>{state.dragging=false;state.lastTrack=null}));$('wipeRange').addEventListener('input',e=>e.target.closest('.wipe').style.setProperty('--wipe',e.target.value+'%'));$('timeline').addEventListener('click',e=>showTimePoint(e.target.closest('button')));$('timeProof').addEventListener('click',showProof);$('proofBtn').addEventListener('click',showProof);
  $('generateBtn').addEventListener('click',()=>generate());$('finishBtn').addEventListener('click',()=>generate());$('resultProof').addEventListener('click',showMatchProof);$('proofContent').addEventListener('click',e=>{if(!navigator.onLine&&e.target.closest('a')){e.preventDefault();toast('当前离线，来源文字仍保留，联网后可打开原文')}});$('resultPlay').addEventListener('click',()=>state.audio&&engine.playBuffer(state.audio.buffer,()=>{if(state.voice)engine.playBuffer(state.voice,()=>{$('resultPlay').textContent='▶ 试听 30 秒《我的京声》'});else $('resultPlay').textContent='▶ 试听 30 秒《我的京声》'}));$('downloadWav').addEventListener('click',()=>state.audio&&download(wav(state.audio.buffer),state.pulse.pulseId+'-我的京声.wav'));$('downloadPng').addEventListener('click',()=>state.pulse&&$('resultCanvas').toBlob(b=>download(b,state.pulse.pulseId+'-结果卡.png'),'image/png'));$('openArtifacts').addEventListener('click',()=>openArtifact());$('addToday').addEventListener('click',()=>{if(!state.pulse)return;collective.add(state.pulse);$('addToday').disabled=true;$('addToday').textContent='已匿名加入今日京声';toast('只加入匿名节奏摘要，不含定位或录音')});
  $('drawPostcard').addEventListener('click',drawPostcard);$('openPostcardArtifact').addEventListener('click',()=>{open('postcardModal',false);openArtifact('postcard')});
  $('artifactTypes').addEventListener('click',e=>{const b=e.target.closest('[data-artifact]');if(b)openArtifact(b.dataset.artifact)});$('downloadSvg').addEventListener('click',()=>{const svg=$('artifactPreview').innerHTML;artifacts.download(svg,state.pulse.pulseId+'-'+state.artifact)});
  $('printArtifact').addEventListener('click',()=>window.print());$('copyPulse').addEventListener('click',async()=>{const url=AxisQR.link(publicBase,state.pulse);try{await navigator.clipboard.writeText(url);toast('NFC / QR 回访链接已复制')}catch(_){prompt('复制回访链接',url)}});
  $('recordVoice').addEventListener('click',toggleVoice);$('playVoice').addEventListener('click',()=>state.voice&&engine.playBuffer(state.voice,()=>toast('声音落款试听结束')));$('deleteVoice').addEventListener('click',async()=>{state.voice=null;if(state.pulse){delete state.pulse.voiceSeal;await renderResult()}document.querySelector('.voice-seal')?.classList.remove('recording','ready');$('voiceStatus').textContent='等待声音落款';$('recordVoice').textContent='● 开始录制';$('playVoice').disabled=true;$('deleteVoice').disabled=true;const c=$('voiceCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height);toast('一句京声已从内存与文创预览中删除')});
  $('playToday').addEventListener('click',playToday);
  $('startLocation').addEventListener('click',()=>{walk.start();$('walkStatus').textContent='正在等待位置与稳定停留判定…'});$('manualWalk').addEventListener('click',()=>$('walkStatus').textContent='手动到达已启用，请逐章确认');$('motionBtn').addEventListener('click',async()=>toast(await walk.startMotion()?'行走节律已启用':'设备未授权或不支持运动传感器'));$('walkNodes').addEventListener('click',e=>{const b=e.target.closest('[data-arrive]');if(b)walk.confirm(b.dataset.arrive,'manual')});
  ['studyA','studyB'].forEach(id=>$(id).addEventListener('change',()=>drawStudy(id==='studyA'?'A':'B')));document.querySelectorAll('[data-study-play]').forEach(b=>b.addEventListener('click',async()=>{const id=$(b.dataset.studyPlay==='A'?'studyA':'studyB').value,old=engine.nodeIndex;engine.nodeIndex=byId[id].index;await engine.preview('qin');engine.nodeIndex=old}));
  document.addEventListener('keydown',e=>{if(document.body.classList.contains('curator-mode'))armCuratorIdle();if(e.code==='Space'&&state.entered){e.preventDefault();engine.playing?engine.pause():engine.start()}if(state.entered&&e.key==='ArrowLeft')selectNode(Math.min(10,state.current+1),true);if(state.entered&&e.key==='ArrowRight')selectNode(Math.max(0,state.current-1),true);if(state.entered&&/^[1-9]$/.test(e.key))selectNode(Number(e.key)-1,true);if(e.key==='Escape'){document.querySelectorAll('.open').forEach(el=>{if(!el.classList.contains('awakening'))open(el.id,false)})}});
  document.addEventListener('pointerdown',()=>{if(document.body.classList.contains('curator-mode'))armCuratorIdle()},{passive:true});
  const raw=initialHash;if(raw.startsWith('pulse=')){try{state.pendingPulse=AxisQR.decode(raw.slice(6));$('enterBtn').querySelector('b').childNodes[0].nodeValue='进入并恢复京声'}catch(e){console.warn('Invalid pulse',e)}}else{const hp=new URLSearchParams(raw),n=hp.get('node');if(n&&byId[n])selectNode(byId[n].index,false)}
  if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('SW',e)));
})();
