(function(global){
  'use strict';
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),midi=n=>440*Math.pow(2,(n-69)/12);
  function hash(text){let h=2166136261>>>0;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
  function rng(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
  function env(g,t,a,l,d,r=.08){g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,l),t+a);g.gain.setValueAtTime(Math.max(.0002,l*.68),Math.max(t+a,t+d-r));g.gain.exponentialRampToValueAtTime(.0001,t+d)}
  function noise(ctx,d,seed){const b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*d),ctx.sampleRate),x=b.getChannelData(0),r=rng(seed);for(let i=0;i<x.length;i++)x[i]=r()*2-1;return b}
  function out(ctx,dest,pan){const p=ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain();if(p.pan)p.pan.value=clamp(pan,-.85,.85);p.connect(dest);return p}
  function osc(ctx,dest,type,f,t,d,l,a=.01,detune=0){const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.detune.value=detune;env(g,t,a,l,d);o.connect(g).connect(dest);o.start(t);o.stop(t+d+.05)}
  function voice(ctx,dest,id,note,t,dur,vel,seed,pan){const f=midi(note),o=out(ctx,dest,pan),r=rng(seed),d=Math.max(.09,dur),v=clamp(vel,.015,.5);
    if(id==='qin'){const lp=ctx.createBiquadFilter();lp.type='lowpass';lp.frequency.value=1800;lp.connect(o);osc(ctx,lp,'triangle',f,t,d,v,.006,-5);osc(ctx,lp,'sine',f*2.01,t,d*.7,v*.34,.004,4);osc(ctx,lp,'sine',f*.5,t,d*.86,v*.2,.01)}
    else if(id==='pipa'){const hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=150;hp.connect(o);[0,.038,.076].forEach((q,i)=>osc(ctx,hp,i===2?'sine':'triangle',f*(1+i*.006),t+q,Math.min(.82,d),v*(i?.2:.72),.004,(r()-.5)*5))}
    else if(id==='xiao'||id==='dizi'){const bp=ctx.createBiquadFilter(),g=ctx.createGain(),s=ctx.createBufferSource();bp.type='bandpass';bp.frequency.value=id==='dizi'?f*3.3:f*1.8;bp.Q.value=id==='dizi'?2.3:1.1;s.buffer=noise(ctx,d,seed);env(g,t,.05,v*(id==='dizi'?.12:.18),d,.14);s.connect(bp).connect(g).connect(o);s.start(t);s.stop(t+d+.02);osc(ctx,o,id==='dizi'?'triangle':'sine',f,t,d,v*(id==='dizi'?.68:.82),id==='dizi'?.035:.12,(r()-.5)*6)}
    else if(id==='sheng'){[0,7,12].forEach((semi,i)=>osc(ctx,o,i===1?'triangle':'sine',midi(note+semi),t,d,v/(1.65+i*.5),.15,(r()-.5)*5))}
    else if(id==='bell'||id==='stone'){(id==='bell'?[1,2.71,4.06,5.43]:[1,1.49,2.96]).forEach((q,i)=>osc(ctx,o,'sine',f*q,t,Math.min(d*(1.2+i*.3),4),v/(1+i*.72),.004))}
    else{const g=ctx.createGain(),z=ctx.createOscillator();z.type='sine';z.frequency.setValueAtTime(f*.62,t);z.frequency.exponentialRampToValueAtTime(Math.max(42,f*.22),t+.16);env(g,t,.003,v,Math.min(.58,d),.18);z.connect(g).connect(o);z.start(t);z.stop(t+.64);const s=ctx.createBufferSource(),lp=ctx.createBiquadFilter(),ng=ctx.createGain();s.buffer=noise(ctx,.16,seed);lp.type='lowpass';lp.frequency.value=520;env(ng,t,.002,v*.36,.16,.08);s.connect(lp).connect(ng).connect(o);s.start(t);s.stop(t+.18)}
  }
  function drone(ctx,dest,note,t,dur,level,pan=0){const o=out(ctx,dest,pan),f=midi(note);osc(ctx,o,'sine',f,t,dur,level,.18,-2);osc(ctx,o,'sine',f*2,t,dur,level*.16,.24,3)}
  function makeBus(ctx,volume=.78){const input=ctx.createGain(),tone=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor(),master=ctx.createGain(),an=ctx.createAnalyser(),delay=ctx.createDelay(1),feed=ctx.createGain(),wet=ctx.createGain();tone.type='lowpass';tone.frequency.value=8600;tone.Q.value=.35;comp.threshold.value=-18;comp.knee.value=14;comp.ratio.value=5;comp.attack.value=.006;comp.release.value=.22;master.gain.value=volume;an.fftSize=1024;delay.delayTime.value=.24;feed.gain.value=.17;wet.gain.value=.16;input.connect(tone).connect(comp);input.connect(delay);delay.connect(feed).connect(delay);delay.connect(wet).connect(tone);comp.connect(master).connect(an).connect(ctx.destination);return{input,master,analyser:an,wet,tone}}
  class AxisAudioEngine{
    constructor(params,onTick){this.p=params;this.onTick=onTick||(()=>{});this.active=new Set(['qin','xiao','sheng']);this.mainTimbre='qin';this.score=null;this.performance=null;this.nodeIndex=0;this.playing=false;this.volume=params.mix.default_volume;this.reverb=.42;this.tempoFactor=1;this.phraseCycle=0;this.renderCache=new Map()}
    async init(){if(this.ctx){if(this.ctx.state==='suspended')await this.ctx.resume();return}const AC=global.AudioContext||global.webkitAudioContext;if(!AC)throw Error('AudioContext unavailable');this.ctx=new AC();Object.assign(this,makeBus(this.ctx,this.volume));await this.ctx.resume()}
    setScore(score){this.score=score}
    setSemantic(semantic){this.semantic=semantic||{};if(this.semantic.timePulse)this.setTempoFactor(.92);if(this.wet)this.wet.gain.setTargetAtTime(clamp(.04+this.reverb*.3+(this.semantic.reverbAdd||0),.02,.42),this.ctx.currentTime,.08)}
    setPerformance(p){this.performance=p}
    setMainTimbre(id){this.mainTimbre=id;if(!this.active.has(id)){const a=[id,...this.active].slice(0,4);this.active=new Set(a)}this.onTick(this.snapshot())}
    setEnsemble(ids){this.active=new Set(ids.slice(0,4));this.mainTimbre=ids[0]||'qin';this.onTick(this.snapshot())}
    toggleInstrument(id){if(this.active.has(id)){if(this.active.size>1)this.active.delete(id)}else{if(this.active.size>=4)return false;this.active.add(id)}this.preview(id);this.onTick(this.snapshot());return true}
    async intro(){await this.init();const t=this.ctx.currentTime+.03,theme=[64,64,67,69,72];voice(this.ctx,this.input,'bell',52,t,2.1,.12,21,-.5);voice(this.ctx,this.input,'sheng',48,t,2.6,.105,22,.08);theme.forEach((note,i)=>voice(this.ctx,this.input,i<2?'qin':'xiao',note,t+[0,.3,.62,.94,1.3][i],i===4?1.45:.56,.16+(i===4?.03:0),23+i,(i-2)/7))}
    async preview(id){await this.init();const es=this.melodyForNode(this.nodeIndex),t=this.ctx.currentTime+.03;(es.length?es.slice(0,4):[{pitchMidi:60,durationBeats:1,velocity:.5},{pitchMidi:64,durationBeats:1,velocity:.5},{pitchMidi:67,durationBeats:1,velocity:.5}]).forEach((e,i)=>voice(this.ctx,this.input,id,e.pitchMidi,t+i*.19,Math.min(1.4,e.durationBeats*.48),.2,hash(id+i+e.pitchMidi),i*.22-.34))}
    async previewTheme(){await this.init();const es=this.melodyForNode(10),t=this.ctx.currentTime+.04,beat=.43,lead=this.leadForNode(10);if(!es.length)return;drone(this.ctx,this.input,48,t,4.1,.018,0);es.forEach(e=>this.scheduleEvent(this.ctx,this.input,e,t+e.phraseBeat*beat,lead,.72,{durationFactor:1.05,harmony:e.phraseRole==='cadence',bass:false}))}
    playHistory(nodeId,depth=2){if(!this.ctx)return;const index=11-Number(nodeId.slice(1)),pick=id=>{const es=this.eventsForNode(11-Number(id.slice(1)));return es[Math.floor(es.length*.48)]},t=this.ctx.currentTime+.04;
      if(nodeId==='N06'){const e=pick('N06');['drum','bell','stone','sheng','xiao','dizi','qin'].forEach((id,i)=>this.scheduleEvent(this.ctx,this.input,e,t+i*.1,id,.58))}
      else if(nodeId==='N04'){['N04','N06','N08'].forEach((id,i)=>{const e=pick(id);if(e)this.scheduleEvent(this.ctx,this.input,e,t+i*.52,i===0?'qin':i===1?'bell':'stone',.68)})}
      else if(nodeId==='N02'){const e=pick('N02');[0,.52,1.04,1.56].forEach((q,i)=>this.scheduleEvent(this.ctx,this.input,e,t+q,i%2?'stone':'bell',.35))}
      else if(nodeId==='N03'){const es=this.eventsForNode(index);for(let i=0;i<12;i++){const e=es[(i*7)%es.length];if(e)this.scheduleEvent(this.ctx,this.input,e,t+i*.11,i%3?'qin':'stone',.22)}}
      else{const e=pick(nodeId);if(e)this.scheduleEvent(this.ctx,this.input,e,t,nodeId==='N11'?'xiao':nodeId==='N01'?'qin':'stone',depth===3?.52:.36)}}
    eventsForNode(index){const id='N'+String(11-index).padStart(2,'0');return this.score?.events.filter(e=>e.nodeId===id)||[]}
    profileForNode(index){const id='N'+String(11-index).padStart(2,'0'),cfg=this.p.score?.node_motifs?.[id]||{},node=this.p.nodes?.find(n=>n.id===id)||{};return{id,name:cfg.name||node.cn||id,tempo:cfg.tempo||76,phraseBeats:cfg.phrase_beats||8,accent:cfg.accent||this.mainTimbre,kind:node.kind||'殿',zone:node.zone||'',act:index<=4?1:index<=7?2:3,energy:node.narrative?.energy??.6}}
    melodyForNode(index){const events=this.eventsForNode(index).filter(e=>e.melodicPriority!==false),groups=new Map();events.forEach(e=>{if(!groups.has(e.motifStep))groups.set(e.motifStep,[]);groups.get(e.motifStep).push(e)});let previous=null;return[...groups].sort((a,b)=>a[0]-b[0]).map(([,group])=>{const sorted=[...group].sort((a,b)=>a.pitchMidi-b.pitchMidi||b.velocity-a.velocity||a.id.localeCompare(b.id)),source=group.find(e=>e.pureStep)||sorted[Math.floor((sorted.length-1)*.55)];let pitch=source.pitchMidi;if(previous!==null){while(pitch-previous>7)pitch-=12;while(previous-pitch>7)pitch+=12}pitch=clamp(pitch,48,88);const shift=pitch-source.pitchMidi;previous=pitch;return{...source,pitchMidi:pitch,harmony:(source.harmony||[]).map(n=>n+shift)}})}
    leadForNode(index,activeOverride){const selected=activeOverride?.length?[...activeOverride]:[...this.active],melodic=['qin','pipa','xiao','dizi','sheng','bell','stone'];if(melodic.includes(this.mainTimbre)&&selected.includes(this.mainTimbre))return this.mainTimbre;const p=this.profileForNode(index);if(melodic.includes(p.accent)&&selected.includes(p.accent))return p.accent;return selected.find(id=>melodic.includes(id))||(['sheng','bell','qin'][p.act-1])}
    phraseExcerpt(events,index,speed=0){const p=this.profileForNode(index),target=p.id==='N06'?6:p.id==='N05'?3:p.kind==='门'?4:p.act===3?4:5,count=Math.max(3,target-(speed>.72?1:0));if(events.length<=count)return[...events];const opening=events.slice(0,Math.max(2,count-1)),closing=events[events.length-1];return opening.includes(closing)?opening:[...opening,closing]}
    previousNode(index){const order=this.performance?.routeOrder||[],prior=order.filter(i=>i!==index);return prior.length?prior[prior.length-1]:null}
    paletteForNode(index,activeOverride){const p=this.profileForNode(index),maps={N11:['xiao','drum','sheng'],N10:['drum','sheng','pipa'],N09:['pipa','drum','sheng'],N08:['drum','bell','sheng'],N07:['sheng','stone','pipa'],N06:['bell','stone','sheng','pipa'],N05:['xiao','qin','sheng'],N04:['stone','pipa','bell'],N03:['qin','xiao','stone'],N02:['stone','bell','qin'],N01:['qin','xiao','sheng']};const stage=maps[p.id]||[p.accent,'qin','sheng'],selected=activeOverride?.length?[...activeOverride]:[...this.active],ordered=[...selected.filter(id=>stage.includes(id)),...stage,...selected];return[...new Set(ordered)].slice(0,4)}
    setNode(node,index){this.nodeIndex=index;this.phraseCycle=0;if(this.playing&&this.ctx){this.phraseStart=this.ctx.currentTime+.035+(this.semantic?.silenceLeadMs||0)/1000;this.nextPhraseEvent=0;this.playArrival(index)}this.onTick(this.snapshot())}
    playArrival(index){const es=this.phraseExcerpt(this.melodyForNode(index),index,.9),p=this.profileForNode(index),lead=this.leadForNode(index),t=this.ctx.currentTime+.025;if(!es.length)return;es.slice(0,3).forEach((e,i)=>this.scheduleEvent(this.ctx,this.input,e,t+[0,.31,.72][i],lead,(.62+i*.05)*(p.energy+.28),{realtime:true,nodeIndex:index,harmony:i===2}))}
    setTempoFactor(v){this.tempoFactor=clamp(v,.72,1.38)}
    setVolume(v){this.volume=clamp(Number(v),0,1);if(this.master)this.master.gain.setTargetAtTime(this.volume,this.ctx.currentTime,.04)}
    setReverb(v){this.reverb=clamp(Number(v),0,1);if(this.wet)this.wet.gain.setTargetAtTime(.04+this.reverb*.3,this.ctx.currentTime,.05)}
    async start(){await this.init();if(this.playing)return;this.playing=true;this.phraseStart=this.ctx.currentTime+.05;this.cycleStart=this.phraseStart;this.nextPhraseEvent=0;this.phraseCycle=0;this.playArrival(this.nodeIndex);this.timer=setInterval(()=>this.schedule(),45);this.onTick(this.snapshot())}
    pause(){this.playing=false;clearInterval(this.timer);this.onTick(this.snapshot())}
    async restart(){this.pause();await this.start()}
    schedule(){if(!this.playing||!this.score)return;const melody=this.melodyForNode(this.nodeIndex),p=this.profileForNode(this.nodeIndex);if(!melody.length)return;const beat=60/(p.tempo*this.tempoFactor),phraseDur=melody[0].phraseBeats*beat,lead=this.leadForNode(this.nodeIndex),palette=this.paletteForNode(this.nodeIndex),response=palette.find(id=>id!==lead&&id!=='drum'),priorIndex=this.previousNode(this.nodeIndex),prior=priorIndex===null?[]:this.melodyForNode(priorIndex);while(this.nextPhraseEvent<melody.length){const e=melody[this.nextPhraseEvent],t=this.phraseStart+e.phraseBeat*beat;if(t>this.ctx.currentTime+.24)break;this.scheduleEvent(this.ctx,this.input,e,Math.max(t,this.ctx.currentTime+.006),lead,.72+p.energy*.3,{realtime:true,nodeIndex:this.nodeIndex,harmony:e.phraseRole==='cadence'});if(e.phraseRole==='opening'){const pedal={...e,pitchMidi:Math.max(43,e.pitchMidi-12),durationBeats:Math.min(6,e.phraseBeats*.7),bassWeight:.15};this.scheduleEvent(this.ctx,this.input,pedal,Math.max(t,this.ctx.currentTime+.006),p.act===3?'qin':'sheng',.2,{realtime:true,durationFactor:1.35,bass:false});if(p.kind==='门')this.scheduleEvent(this.ctx,this.input,{...e,pitchMidi:Math.max(43,e.pitchMidi-24),durationBeats:.45},Math.max(t,this.ctx.currentTime+.006),'drum',.24+p.energy*.1,{realtime:true,durationFactor:.62,bass:false})}const priorEvent=prior.find(x=>x.motifStep===e.motifStep);if(response&&priorEvent&&(e.motifStep===4||e.phraseRole==='cadence'))this.scheduleEvent(this.ctx,this.input,priorEvent,Math.max(t+.055,this.ctx.currentTime+.006),response,.14,{realtime:true,nodeIndex:priorIndex,durationFactor:1.08,bass:false});this.nextPhraseEvent++}if(this.nextPhraseEvent>=melody.length&&this.ctx.currentTime>this.phraseStart+phraseDur-.26){this.phraseStart+=phraseDur;this.cycleStart=this.phraseStart;this.nextPhraseEvent=0;this.phraseCycle++}this.onTick(this.snapshot())}
    scheduleEvent(ctx,dest,e,t,id,mod=.8,options={}){const sem={...(e.semanticMod||{}),...(options.realtime?(this.semantic||{}):{})},durationFactor=options.durationFactor||1,dur=Math.min(4,e.durationBeats*.56*durationFactor*(.82+this.reverb*.35)*(1+(sem.intimacy||0)*.08)),basePan=((e.motifStep||0)%7-3)/7,pan=options.panReverse?-basePan:basePan;voice(ctx,dest,id,e.pitchMidi,t,dur,e.velocity*.31*mod*(sem.energyFactor||1),hash(e.id+'|'+id),pan);if(e.timbreRole==='ritual_resonance'&&e.harmony?.length>1&&(options.harmony||e.phraseRole==='cadence'))voice(ctx,dest,id,e.harmony[1],t+.04,dur*1.06,e.velocity*.075*mod,hash(e.id+'h'),-pan*.5);if(options.bass!==false&&e.bassWeight>.38&&id!=='drum'&&(e.phraseRole==='opening'||e.phraseRole==='cadence'))voice(ctx,dest,'sheng',e.pitchMidi-12,t,dur*1.16,e.velocity*.045*mod,hash(e.id+'b'),0)}
    waveform(a){if(!this.analyser)return a.fill(128);this.analyser.getByteTimeDomainData(a);return a}
    snapshot(){return{playing:this.playing,bar:Math.floor(((this.ctx?.currentTime||0)-(this.cycleStart||0))/2)+1,active:[...this.active],mainTimbre:this.mainTimbre,volume:this.volume,reverb:this.reverb,audioState:this.ctx?.state||'closed'}}
    async renderComposition(pulse,targetDuration=30){
      const duration=targetDuration,sr=44100,OAC=global.OfflineAudioContext||global.webkitOfflineAudioContext;
      if(!OAC)throw Error('OfflineAudioContext unavailable');
      const perf=pulse.performanceProfile||{},cacheKey=JSON.stringify({duration,score:this.score?.scoreHash,active:pulse.activeInstruments||[...this.active],main:pulse.mainTimbre||this.mainTimbre,route:perf.routeOrder,dwell:perf.dwellByNode,speed:perf.speedBySegment,visits:perf.visitCountByNode,back:perf.reversalCount,complete:perf.completionRate,history:perf.historyDepthByNode});
      if(this.renderCache.has(cacheKey))return this.renderCache.get(cacheKey);
      const ctx=new OAC(2,sr*duration,sr),bus=makeBus(ctx,.92),rawOrder=perf.routeOrder?.length?perf.routeOrder:[0,1,2,3,4,5,6,7,8,9,10],order=rawOrder.filter((v,i)=>i===0||v!==rawOrder[i-1]),seg=duration/order.length;
      order.forEach((idx,oi)=>{
        const full=this.melodyForNode(idx);if(!full.length)return;
        const p=this.profileForNode(idx),reversed=!!(oi&&idx<order[oi-1]),dwell=clamp((perf.dwellByNode?.[idx]||0)/8000,0,1),speed=clamp(perf.speedBySegment?.[idx]||.25,0,1.2),visits=perf.visitCountByNode?.[idx]||1,historyDepth=perf.historyDepthByNode?.[p.id]||0,durationFactor=clamp(1.05-speed*.22+dwell*.22,.78,1.32),prior=oi?this.melodyForNode(order[oi-1]):[];
        let es=this.phraseExcerpt(full,idx,speed);
        if(reversed){const pitches=[...es].reverse().map(e=>e.pitchMidi);es=es.map((e,j)=>({...e,pitchMidi:pitches[j]}))}
        const selected=pulse.activeInstruments||[...this.active],lead=this.leadForNode(idx,selected),palette=this.paletteForNode(idx,selected),response=palette.find(id=>id!==lead&&id!=='drum');
        es.forEach((e,j)=>{
          const scoreProgress=clamp(e.phraseBeat/Math.max(1,e.phraseBeats),0,.88),t=.045+oi*seg+scoreProgress*seg*.92,mod=(.72+dwell*.28+Math.min(2,visits-1)*.07)*(1-speed*.06);
          this.scheduleEvent(ctx,bus.input,e,t,lead,mod,{nodeIndex:idx,durationFactor,panReverse:reversed,harmony:j===es.length-1});
          const priorEvent=prior.find(x=>x.motifStep===e.motifStep);if(response&&priorEvent&&(j===Math.ceil(es.length*.55)||j===es.length-1)&&p.kind!=='门')this.scheduleEvent(ctx,bus.input,priorEvent,t+.055,response,.12+dwell*.07,{nodeIndex:order[oi-1],durationFactor:1.06,panReverse:!reversed,bass:false});
          if(visits>1&&j===es.length-2)this.scheduleEvent(ctx,bus.input,e,t+Math.min(.24,seg*.08),lead,.18+Math.min(.12,(visits-2)*.04),{nodeIndex:idx,durationFactor:.78,panReverse:!reversed,bass:false});
        });
        const first=es[0];if(!first)return;
        drone(ctx,bus.input,Math.max(43,first.pitchMidi-12),.01+oi*seg,Math.min(seg*1.015,duration-(.01+oi*seg)),.018+p.energy*.004,(p.act-2)*.08);
        const pedal={...first,pitchMidi:Math.max(43,first.pitchMidi-12),durationBeats:Math.min(4.2,seg/.56),bassWeight:.18,phraseRole:'opening'};
        this.scheduleEvent(ctx,bus.input,pedal,.025+oi*seg,p.act===3?'qin':'sheng',.16+p.energy*.07,{nodeIndex:idx,durationFactor:1.28,bass:false});
        if(p.kind==='门')this.scheduleEvent(ctx,bus.input,{...first,pitchMidi:Math.max(43,first.pitchMidi-24),durationBeats:.38,phraseRole:'opening'},.035+oi*seg,'drum',.2+p.energy*.08,{nodeIndex:idx,durationFactor:.62,panReverse:reversed,bass:false});
        else if(p.act===2)this.scheduleEvent(ctx,bus.input,{...first,durationBeats:.42,phraseRole:'opening'},.035+oi*seg,oi%2?'stone':'bell',.1+p.energy*.05,{nodeIndex:idx,durationFactor:.68,bass:false});
        if(dwell>.62){const e=es[es.length-1];this.scheduleEvent(ctx,bus.input,{...e,phraseRole:'cadence'},.045+oi*seg+seg*.87,response||lead,.13+dwell*.08,{nodeIndex:idx,durationFactor:1.18,panReverse:!reversed,bass:false})}
        if(historyDepth>=2){const e=es[Math.min(2,es.length-1)],ritual=['bell','stone','sheng','xiao','dizi','qin'][(idx+historyDepth)%6];this.scheduleEvent(ctx,bus.input,e,.04+oi*seg+seg*.62,ritual,.13+historyDepth*.055,{nodeIndex:idx,durationFactor:1.18,bass:false})}
      });
      const lastIndex=order[order.length-1]??0,last=this.melodyForNode(lastIndex),complete=perf.completionRate??new Set(order).size/11;
      if(last.length){const e={...last[last.length-1],phraseRole:'cadence'},t=duration-1.35,lead=this.leadForNode(lastIndex,pulse.activeInstruments);if(complete>=.8){this.scheduleEvent(ctx,bus.input,{...e,durationBeats:2.4,bassWeight:.7},t,lead,.42,{durationFactor:1.45,harmony:true});if(e.harmony?.[1])this.scheduleEvent(ctx,bus.input,{...e,pitchMidi:e.harmony[1],durationBeats:2.2,bassWeight:.2},t+.04,'sheng',.18,{durationFactor:1.4,bass:false})}else this.scheduleEvent(ctx,bus.input,{...e,durationBeats:.8,bassWeight:.1},duration-.75,'xiao',.22,{durationFactor:.8,bass:false})}
      const buffer=await ctx.startRendering();let peak=0,sum=0,count=0;
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++){const a=Math.abs(d[i]);peak=Math.max(peak,a);sum+=d[i]*d[i];count++}}
      const rms=Math.sqrt(sum/count)||1e-5,target=10**(this.p.mix.target_rms_dbfs/20),ceiling=10**(this.p.mix.peak_ceiling_dbfs/20),gain=Math.min(target/rms,ceiling/Math.max(peak,1e-5));
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]*=gain}
      const frame=Math.max(1,Math.round(sr*.05)),frames=Math.ceil(buffer.length/frame);let near=0,frameCount=0;
      for(let c=0;c<2;c++){const d=buffer.getChannelData(c);for(let start=0;start<d.length;start+=frame){let power=0,n=0;for(let i=start;i<Math.min(d.length,start+frame);i++){power+=d[i]*d[i];n++}if(Math.sqrt(power/Math.max(1,n))<.0032)near++;frameCount++}}
      const result={buffer,stats:{duration,rmsDb:20*Math.log10(rms*gain),peakDb:20*Math.log10(peak*gain),nearSilenceRatio:near/frameCount,gain,silenceWindowMs:50}};this.renderCache.set(cacheKey,result);if(this.renderCache.size>3)this.renderCache.delete(this.renderCache.keys().next().value);return result
    }
    async playBuffer(buffer,onEnded){await this.init();this.pause();const s=this.ctx.createBufferSource();s.buffer=buffer;s.connect(this.input);s.onended=onEnded;s.start();this.renderedSource=s}
  }
  global.AxisAudioEngine=AxisAudioEngine;
})(window);
